baseURL: https://abytecurious.bid
languageCode: en-us
title: A Byte Curious
theme: yourfolio
disableKinds: [RSS, taxonomy, taxonomyTerm]
googleAnalytics: UA-XXXXX-Y

# Menu items
menu:
  main:
  - name: About
    weight: 1
    url: /about
  - name: Contact
    weight: 2
    url: /contact

# Custom params
params:
  env: development
  logoImage: img/logo.png
  logoImageAlt: Yourfolio Theme brand logo
